### PR TITLE
Contributing geniuskb icons

### PR DESCRIPTION
**Pull request by Marin37**
Contributing iconpack similar to my genius keyboard

### CODE REVIEW

**Comment by jonaskohl** [comment]
Thanks for your icon pack contribution!

I fixed some things in your pull request:

- In `geniuskb_dark` I converted `scroll0.png` to `scroll0.ico`
- In `geniuskb_light` I fixed the height of `num1.ico` to be 16px instead of 17px

**Comment by jonaskohl** [comment]
Oh and apparently your ICO files were just renamed PNG files, so I quickly converted them!

**Comment by Marin37** [comment]
Oh ok, I always supposed that after renaming "i can open it anyway" was
that it converted succesfully, noted and sorry for the inconvenience!
Anyways thank *you *for such a simple yet very useful program!

**Comment by jonaskohl** [comment]
No problem! I added a section to this repo's README to clarify this

**Pull request merged**
